### ISSUE TITLE
Cannot execute python after running create-osx-bundle.sh

### ISSUE THREAD

**Issue by nusli** [kivy/kivy-sdk-packager#63]
I wanted to package my application and ran create-osx-bundle.sh. The script seemed to have run to completion. However, when I proceeded to the next steps outlined in the osx/readme.md, any attempt to run a python command fails with the Error:
`ImportError: No module named site`

This only happens when the virtual environment is activated (_kivy-sdk-packager/osx/Parcoursplaner.app/Contents/Resources/venv/bin_). With the venv deactivated python still functions normally. **The same issue occurs when i try to run buildozer**

The script threw a couple errors for multiple .DS_Store files, though i suppose that's not causing my issue:
`+ osxrelocator -r . /usr/local/lib/ @executable_path/Contents/lib/
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: './Contents/Frameworks/Python.framework/Versions/3.7/.DS_Store': The end of the file was unexpectedly encountered`

I piped the logs into a .txt file. I attached these logs aswell as the statements that were written into the terminal as files to this issue.
[log_shell.txt](https://github.com/kivy/kivy-sdk-packager/files/6414590/log_shell.txt)
[log.txt](https://github.com/kivy/kivy-sdk-packager/files/6414591/log.txt)

## My Setup:

**OS: MacOS 11.2.1**

**Shell script flags: ./create-osx-bundle.sh -n Parcoursplaner -v "0.0.1a" -a "Linus" -g 0**

**Comment by matham** [comment]
I don't think this has been tried with buildozer recently so I'm not surprised it's not working there.

As for your issue, it's impossible to troubleshoot this kind of issue over a github issue. But I would suggest you look at the activate (perhaps post it here) script. And please make sure you're following the exact steps to activate the venv (pushd etc).

I would also consider starting from an existing Kivy.dmg. You can see a full example [here](https://github.com/kivy/kivy_pong_demo/blob/main/.github/workflows/pythonapp.yml#L94). I would also take a look at how we [generate Kivy.app](https://github.com/kivy/kivy/blob/master/.ci/osx_ci.sh) to see if you're doing something wrong.

**Comment by nusli** [comment]
I am using zsh now. Running activate throws this error:

activate:cd :60: string not in pwd: ./../../../Frameworks/Python.framework/Versions/3.7

Here is the corresponding line:
`export PYTHONHOME="$(cd "$(dirname "$BASH_SOURCE")"/../../../Frameworks/Python.framework/Versions/3*; echo "$(pwd)")"`

Changing `3*` to `3.7` solved the issue. I doubt that it was intended for a user to have to manually change the script though.
Nonetheless I still get the ImportError.

**Comment by matham** [comment]
Hmm, did you try the kivy built Kivy.dmg file? Because that is the intended way for users to interact with it. Building a bundle from scratch is harder because more things are likely to go wrong. Especially if your local system is not completely clean, like on the CI.

Ultimately, we're playing a game of cat and mouse because virtualenvs don't officially support what we're doing, so with any updates we have to make sure we're patching it correctly. So yeah, some debugging is required if things break.

**Comment by matham** [comment]
Given that it [works on the CI](https://github.com/kivy/kivy/runs/2523653805?check_suite_focus=true) that I linked to above, I suspect it is something with your env or installation.  We [test the generated app](https://github.com/kivy/kivy/runs/2523760311?check_suite_focus=true), so it definitely works.

**Comment by matham** [comment]
You probably didn't install them like a python package!? You need to install them so it gets installed to site-packages, like normal python packages. Otherwise, python wouldn't find them, even if it's in the current directory.

This is why I made https://github.com/kivy/kivy_pong_demo. Personally, I don't have a MAC so I can't test, but I would first start with https://github.com/kivy/kivy_pong_demo/releases to make sure the compiled dmg works. Then I would use that project as a base or test platform for your app to see what you're potentially doing that breaks it. 

Specifically, notice how https://github.com/kivy/kivy_pong_demo/blob/main/.github/workflows/pythonapp.yml#L119 installs the project (using its `setup.py`) so python can run it. Take a look at the other steps as well.

**Comment by nusli** [comment]
I installed it using pip, but maybe i have an error in my setup.py. I'll try the pong_demo out :)

**Comment by nusli** [comment]
So i created a .dmg file for the pong_demo and it worked, but when I tried to add another .py file to the pong_demo app, the file couldn't be imported again.
It turns out I have to specify imports of python files differently for local development execution and for the .dmg package.

For example:
If I run _main.py_ directly, I import the file like this: `from mymodule import myfunction`.
But in order for the App to function I need to import like this: `from kivy_pong_demo.mymodule import myfunction`.

Is there a way to make an import statement work for both cases or automatically transforming the import statements before/during build? (besides writing my own script of course ;) )

**Comment by matham** [comment]
I think this is a issue with how you use imports.

* Importing stuff from a package using the `from kivy_pong_demo.mymodule import myfunction` syntax always works if `kivy_pong_demo` is a known package.
* Importing stuff from within a package referencing other sub-packages or modules using the `from .mymodule import myfunction` syntax works if the script you're running is running as a module, not as a script. I.e. this won't work if you're running `python main .py`, but it would work if you're running it as `python -m kivy_pong_demo.main`.
* What you are doing, simply importing `mymodule import myfunction`, this works only if the current folder is on the PYTHONPATH, but doesn't work in general and is not a way I'd recommend to use to import stuff from packages. I imagine it worked for you in your dev env simply by accident due to what your current working directory was. However, it doesn't work in general.

**Comment by nusli** [comment]
I got it to work but I have run into another problem that I can't find a solution for:
In the packaged app everything looks blurry as if all images have been drawn and then increased in size. I have tried different metrics and modified the size of the widgets but it always remains blurry.
I noticed that this also occurs on the pong app.

Is there some kind of OS setting that I could modify or is there an issue with the startup script?

**Screenshot of the app when run through main.py:**
<img width="799" alt="Screenshot normal" src="https://user-images.githubusercontent.com/25670567/117856569-11478f00-b28c-11eb-8147-395b72078d30.png">

**Screenshot of the app when run through yourapp:**
<img width="800" alt="screenshot scaled" src="https://user-images.githubusercontent.com/25670567/117856670-30462100-b28c-11eb-9352-aa1eeae4b623.png">

**Comment by matham** [comment]
When running the app normally, are you using master or 2.0.0? Because when you're using Kivy.app you're probably using 2.0.0. You can get a Kivy.app from latest master [here](https://kivy.org/downloads/ci/osx/app/).

Otherwise, I'm not sure because I don't personally use a mac. I would look in the kivy repo issues to see other reports of blurriness. You can also try asking on discord.

**Comment by Julian-O** [comment]
Closing as support issue.
