### ISSUE TITLE
Update MACOSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by Arthedian** [kivy/kivy-sdk-packager#89]
Hi, 
so as per https://github.com/libsdl-org/SDL/issues/7563 the MACOSX_DEPLOYMENT_TARGET needs to be updated with the new macOS versions. Is there any meantime hot fix? I tried to update it in "create-osx-bundle.sh" but sadly it wasn't enough. Where else should I updated it?

**Comment by misl6** [comment]
Hi @Arthedian !

PR https://github.com/kivy/kivy/pull/8191 will take care of it (since `kivy-sdk-packager` now uses the build script from `kivy/kivy`)

https://github.com/kivy/kivy-sdk-packager/blob/0410fa007843252d68e8f45d1f4da6ab6c203522/osx/create-osx-bundle.sh#L122-L127

As a temp workaround, you can clone the previously mentioned PR repo, and start the `create-osx-bundle.sh` script with `--kivy /path/to/cloned/kivy-repo`

**Comment by Arthedian** [comment]
It's in the main branch of Kivy, so that's good. But you still need to change version in this repo on line 131 of create-osx-bundle.sh file to fix the problem. Am I right?

**Comment by Arthedian** [comment]
https://github.com/kivy/kivy-sdk-packager/pull/90
